function spike_xqs_example1_SpikeXqsExample1(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',ub='648CBE981B9FD282F13E6829D58AC60A.cache.html',xb='<script defer="defer">spike_xqs_example1_SpikeXqsExample1.onInjectionDone(\'spike.xqs.example1.SpikeXqsExample1\')<\/script>',Cb='<script id="',A='=',q='?',tb='ACCEA922E7F222BF1EA9119BBC079307.cache.html',C='Bad handler "',wb='DOMContentLoaded',vb='FCE04A26C1A8E5BE94FC57905535ED00.cache.html',o='SCRIPT',Bb='__gwt_marker_spike.xqs.example1.SpikeXqsExample1',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',Ab='end',mb='gecko',ob='gecko1_8',yb='gwt.hybrid',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',rb='hosted.html?spike_xqs_example1_SpikeXqsExample1',lb='ie6',kb='ie8',ab='iframe',t='img',bb="javascript:''",qb='loadExternalRefs',v='meta',eb='moduleRequested',zb='moduleStartup',jb='msie',w='name',gb='opera',db='position:absolute;width:0;height:0;border:none',ib='safari',sb='selectingPermutation',m='spike.xqs.example1.SpikeXqsExample1',x='startup',pb='unknown',fb='user.agent',hb='webkit';var Eb=window,k=document,Db=Eb.__gwtStatsEvent?function(a){return Eb.__gwtStatsEvent(a)}:null,sc,ic,dc,cc=l,lc={},vc=[],rc=[],bc=[],oc,qc;Db&&Db({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!Eb.__gwt_stylesLoaded){Eb.__gwt_stylesLoaded={}}if(!Eb.__gwt_scriptsLoaded){Eb.__gwt_scriptsLoaded={}}function hc(){var b=false;try{b=Eb.external&&(Eb.external.gwtOnLoad&&Eb.location.search.indexOf(yb)==-1)}catch(a){}hc=function(){return b};return b}
function kc(){if(sc&&ic){var c=k.getElementById(m);var b=c.contentWindow;if(hc()){b.__gwt_getProperty=function(a){return ec(a)}}spike_xqs_example1_SpikeXqsExample1=null;b.gwtOnLoad(oc,m,cc);Db&&Db({moduleName:m,subSystem:x,evtGroup:zb,millis:(new Date()).getTime(),type:Ab})}}
function fc(){var j,h=Bb,i;k.write(Cb+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){cc=f(j.src)}if(cc==l){var e=k.getElementsByTagName(s);if(e.length>0){cc=e[e.length-1].href}else{cc=f(k.location.href)}}else if(cc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=cc+u;cc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function pc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}lc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{qc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{oc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function uc(d,e){var a=bc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function ec(d){var e=rc[d](),b=vc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(qc){qc(d,a,e)}throw null}
var gc;function jc(){if(!gc){gc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);Db&&Db({moduleName:m,subSystem:x,evtGroup:zb,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(cc+tc)}}
rc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){if(document.documentMode>=8){return kb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return lb}}}}else if(d.indexOf(mb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ob}return mb}return pb};vc[fb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};spike_xqs_example1_SpikeXqsExample1.onScriptLoad=function(){if(gc){ic=true;kc()}};spike_xqs_example1_SpikeXqsExample1.onInjectionDone=function(){sc=true;Db&&Db({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:Ab});kc()};fc();var tc;if(hc()){if(Eb.external.initModule&&Eb.external.initModule(m)){Eb.location.reload();return}tc=rb}pc();Db&&Db({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:sb});if(!tc){try{uc([lb],tb);uc([mb],ub);uc([ob],ub);uc([gb],ub);uc([ib],ub);uc([kb],vb);tc=bc[ec(fb)]}catch(a){return}}var nc;function mc(){if(!dc){dc=true;kc();if(k.removeEventListener){k.removeEventListener(wb,mc,false)}if(nc){clearInterval(nc)}}}
if(k.addEventListener){k.addEventListener(wb,function(){jc();mc()},false)}var nc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){jc();mc()}},50);Db&&Db({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:Ab});Db&&Db({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:nb});k.write(xb)}
spike_xqs_example1_SpikeXqsExample1();